/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.sql.ResultSet;
import java.sql.SQLException; 
import Proccess.CT_CongViec;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Endy
 */
public class FrmCapNhatCongViec extends javax.swing.JFrame {

    /**
     * Creates new form FrmCapNhatCongViec
     */
    private final CT_CongViec ct = new CT_CongViec(); 
    private boolean cothem = true; 
    private final DefaultTableModel tableModel = new DefaultTableModel();
    
    public FrmCapNhatCongViec() {
        initComponents();
        String[] colsName  = {"Mã công việc", "Tiến độ công việc", "Mức độ hoàn thành"};
        
        tableModel.setColumnIdentifiers(colsName);
        tblCTCV.setModel(tableModel);
        try{
            ShowData();
        }catch(SQLException ex){
            Logger.getLogger(FrmCapNhatCongViec.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ShowDataCombo();
        setNull();
        setKhoa(true);
        setButton(true);
    }
    
    // Ham do du lieu vao combobox
    public final void ShowDataCombo(){
        ResultSet result = null;
        
        try{
             result = ct.ShowCongviec();
            while (result.next()){
                cbxMacv.addItem(result.getString("MACV"));
            }
        }catch (SQLException e){
        }
    }

    // Hien thi ten loại theo ma loai trong combobox 
    public void ShowTenloai (String macv) throws SQLException {
        ResultSet result = ct.ShowCongViec(macv);
        if (result.next ()) { // nếu còn đọc tiếp được một dòng dữ liệu
            txtTencv.setText (result.getString("TENCV"));
        }
    }
    

     public final void ShowData() throws SQLException {
        ResultSet result = null; 
        result = ct.ShowCTCongviec();                 
        try{
            ClearData();
            while (result.next()) {
                String rows[] = new String[4];
                rows[0] = result.getString(1);
                rows[1] = result.getString(2);
                rows[2] = result.getString(3);
                tableModel.addRow(rows);
            }
        }catch(Exception e){
            
        }
    }
     
     public void ClearData() throws SQLException {
        //Lay chi Bo dong cuoi cung 
        int n = tableModel.getRowCount() - 1; 
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);  //Remove tung dong
        }
    }

     // Ham xoa trang cac TextField 
    private void setNull() {
        cbxMacv.setSelectedItem(null);
        txtTencv.requestFocus();
        cbxTiendo.requestFocus(); 
        txtMucdo.requestFocus();
    }
    
     //Ham khoa cac TextField 
    private void setKhoa (boolean e){
        cbxMacv.setEnabled(!e); 
        txtTencv.setEnabled(!e); 
        cbxTiendo.setEnabled(!e); 
        txtMucdo.setEnabled(!e);
    }
    
    //Hàm khoa cáE BEtern 
    private void setButton (boolean e){
        btnThem.setEnabled(e);
        btnXoa.setEnabled(e); 
        btnSua.setEnabled(e);
        btnLuu.setEnabled(!e);
        btnHuy.setEnabled(!e);
        btnThoat.setEnabled(e);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTencv = new javax.swing.JTextField();
        cbxTiendo = new javax.swing.JComboBox<>();
        txtMucdo = new javax.swing.JTextField();
        cbxMacv = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTCV = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QUẢN LÝ CHI TIẾT CÔNG VIỆC");

        jLabel2.setText("Tiến độ công việc");

        jLabel3.setText("Mức độ hoàn thành");

        jLabel5.setText("Mã công việc");

        cbxTiendo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thực hiện", "Đang tiến hành", "Đã hoàn thành" }));

        cbxMacv.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMacvItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtMucdo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxMacv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTencv, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxTiendo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTencv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxMacv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxTiendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMucdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCTCV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã công việc", "Tiến độ công việc", "Mức độ hoàn thành"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblCTCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCTCVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCTCV);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addGap(41, 41, 41)
                .addComponent(btnXoa)
                .addGap(48, 48, 48)
                .addComponent(btnSua)
                .addGap(46, 46, 46)
                .addComponent(btnLuu)
                .addGap(44, 44, 44)
                .addComponent(btnHuy)
                .addGap(48, 48, 48)
                .addComponent(btnThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoat)
                    .addComponent(btnLuu)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnThem)
                    .addComponent(btnHuy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(231, 231, 231)
                                .addComponent(jLabel1)))
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMacvItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMacvItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxMacvItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        setNull();
        setKhoa (false);
        setButton (false);
        cothem = true;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        String ma = cbxMacv.getSelectedItem().toString();
        try{
            if (ma.length() ==0) {
                JOptionPane.showMessageDialog (null, "Cần chọn 1 sản phảm xóa", "Thông báo", 1);
            }else{
                if(JOptionPane.showConfirmDialog (null, "Bạn có muốn xóa sản phẩm " + ma + " này hay không?", "Thông báo", 2) == 0){
                    ct.DeleteData(ma);
                    ClearData();
                    ShowData();
                    setNull();
                }
            }

        }catch(SQLException ex){ Logger.getLogger(FrmCapNhatCongViec.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:

        String mcv = cbxMacv.getSelectedItem().toString();
        if (mcv.length() == 0){
            JOptionPane.showMessageDialog (null, "Vui lòng chọn loại cần sửa", "Thông báo", 1);
        } else {
            setKhoa (false);
            setButton (false);
            cothem = false;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:

        String macv = cbxMacv.getSelectedItem().toString();
        String tiendo = cbxTiendo.getSelectedItem().toString();
        double mucdo;
        mucdo = Integer.parseInt(txtMucdo.getText());
        NumberFormat phantram = NumberFormat.getCurrencyInstance();
        String ptmucdo = phantram.format(mucdo);

        if (macv.length() == 0 || tiendo.length() == 0) {
            JOptionPane.showMessageDialog(null,"Vui lòng nhập mã sản phẩm và tên sản phẩm ", "Thông báo", 1);
        } 
        try {
            if (cothem == true){
                ct.InsertData(macv, tiendo, mucdo);
            }
            else{
                ct.InsertData(macv, tiendo, mucdo);
            }

                ClearData();
                ShowData();
        }
        catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại","Thông báo", 1);
            }
            setNull();
            setKhoa(false);
            setButton(false);
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        setNull();
        setKhoa(true);
        setButton(true);

    }//GEN-LAST:event_btnHuyActionPerformed

    private void tblCTCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCTCVMouseClicked
        // TODO add your handling code here:
        
        try{
            int row = this.tblCTCV.getSelectedRow();
            String macv = (this.tblCTCV.getModel().getValueAt (row, 0)).toString();
            ResultSet rs = ct.ShowCongViec(macv);
            
            if (rs.next()){
                cbxMacv.setSelectedItem(rs.getString("MACV")); 
                txtTencv.setText (rs.getString("TENCV"));
                cbxTiendo.setSelectedItem(rs.getString("TIENDOCONGVIEC"));
                txtMucdo.setText(rs.getString("MUCDOHOANTHANH"));
                txtTencv.setText(rs.getString("TENCV"));
            }
        } catch(SQLException e){}
    }//GEN-LAST:event_tblCTCVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCapNhatCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCapNhatCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCapNhatCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCapNhatCongViec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                new FrmCapNhatCongViec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxMacv;
    private javax.swing.JComboBox<String> cbxTiendo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblCTCV;
    private javax.swing.JTextField txtMucdo;
    private javax.swing.JTextField txtTencv;
    // End of variables declaration//GEN-END:variables
}
